name: Run Daily Python Script

on:
  schedule:
    # Runs at 8 AM every weekday (UTC)
    - cron: '0 2 * * 1-5'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your desired Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your project dependencies

    # Step 4: Run your Python script
    - name: Run daily script
      run: |
        python your_script.py  # Replace 'your_script.py' with the name of your script
